services:
  - type: web
    name: my-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

