services:
  - type: web
    name: my-dashboard
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    autoDeploy: true

