services:
  - type: web
    name: my-dashboard
    env: python
    region: oregon
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: |
      sleep 3 && gunicorn -b 0.0.0.0:$PORT app:app --workers=1 --threads=2 --timeout=120 --log-level=info
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

