name: Auto Sync Prices & Stock

on:
  schedule:
    - cron: "*/30 * * * *"   # Runs every 30 minutes
  workflow_dispatch:         # Allows manual runs from GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install requests

      - name: Run scraper updater
        env:
          SCRAPEROPS_API_KEY: ${{ secrets.SCRAPEROPS_API_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python update_products.py

