name: Run Scraper

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:        # allows manual trigger too

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        env:
          DASHBOARD_URL: ${{ secrets.DASHBOARD_URL }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python update_products.py
